import ListCategories from '@/components/Homepage/ListCategories'
import Layout from '@/layouts/MainLayout'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Change of Needs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="col-md-12 mt-3">
          {/* Kategorilerin listelendiği alan */}
          <ListCategories></ListCategories>
        </div>
      </Layout>
    </>
  )
}
